# Generated by Django 4.2.3 on 2023-12-22 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_dynamicformdata_delete_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicformdata',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
